-- FUNÇÃO DATEDIFF

-- RETORNAR UM INTEIRO CORRESPONDENTE A DIREFENÇA ENTRE DUAS DATAS
-- QUE PODE SER EM NÚMERO DE MINUTOS, HORAS, DIAS, MESES E ANOS

SELECT DATEDIFF(YEAR, '1990-01-01', GETDATE());
-- MOSTRA A DIFERENÇA ENTRA A DATA '1990-01-01' ATÉ ETDATE() (DATA ATUAL)

