CREATE DATABASE MATEUSDOMINGOS_CONSTRUTORA_V2;
GO

USE MATEUSDOMINGOS_CONSTRUTORA_V2;
GO

CREATE TABLE FUNCIONARIO(
	CODIGO INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CPF CHAR(11) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	SEXO CHAR(1) NULL,
	SALARIO MONEY NOT NULL,
	CIDADE  VARCHAR(50) NULL,
	UF CHAR(2) NOT NULL,
	DATA_HORA_CADASTRO DATETIME NOT NULL DEFAULT GETDATE(),
	ATIVO BIT NOT NULL DEFAULT 1,
	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(CODIGO),
	CONSTRAINT UQ_FUNCIONARIO_CPF UNIQUE(CPF),
	CONSTRAINT UQ_FUNCIONARIO_EMAIL UNIQUE(EMAIL),
	CONSTRAINT CK_FUNCIONARIO_CPF CHECK(LEN(CPF)=11),
	/*CONSTRAINT CK_FUNCIONARIO_SEXO CHECK(SEXO='F' OR SEXO='M')*/
	CONSTRAINT CK_FUNCIONARIO_SEXO CHECK(SEXO IN('F','M')),
	CONSTRAINT CK_FUNCIONARIO_DATA_NASCIMENTO CHECK(DATEDIFF( YEAR, DATA_NASCIMENTO, GETDATE() )>=18),
);
GO 

CREATE TABLE DEPENDENTE(
	CODIGO INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(50) NULL,
	PARENTESCO VARCHAR(20) NOT NULL,
	COD_FUNCIONARIO INT NOT NULL,
	CONSTRAINT PK_DEPENDENTE PRIMARY KEY(CODIGO),
	CONSTRAINT FK_DEPENDENTE_FUNCIONARIO FOREIGN KEY(COD_FUNCIONARIO) REFERENCES FUNCIONARIO(CODIGO),
	CONSTRAINT CK_DEPENDENTE_DATA_NASCIMENTO CHECK(DATEDIFF( YEAR, DATA_NASCIMENTO, GETDATE() )<18),
);
GO

CREATE TABLE PROJETO(
	CODIGO INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_TERMINO DATE NULL,
	VALOR MONEY NULL,
	COD_FUNC_GER INT NOT NULL,
	CONSTRAINT PK_PROJETO PRIMARY KEY(CODIGO),
	CONSTRAINT FK_PROJETO FOREIGN KEY(COD_FUNC_GER) REFERENCES FUNCIONARIO(CODIGO),
	CONSTRAINT CK_PROJETO_DATA_TERMINO CHECK(DATA_TERMINO IS NULL OR DATA_TERMINO >= DATA_INICIO),
);
GO

CREATE TABLE FUNCIONARIO_PROJETO(
	CODIGO INT NOT NULL IDENTITY(1,1),
	COD_FUNCIONARIO INT NOT NULL,
	COD_PROJETO INT NOT NULL,
	DATA_ENTRADA DATE NOT NULL,
	DATA_SAIDA DATE NULL,
	NUM_HORAS_TRAB FLOAT NOT NULL,
	CONSTRAINT PK_FUNCIONARIO_PROJETO PRIMARY KEY(CODIGO),
	CONSTRAINT FK_FUNCIONARIO_PROJETO_FUNCIONARIO FOREIGN KEY(COD_FUNCIONARIO) REFERENCES FUNCIONARIO(CODIGO),
	CONSTRAINT FK_FUNCIONARIO_PROJETO_PROJETO FOREIGN KEY(COD_PROJETO) REFERENCES PROJETO(CODIGO),
);
