CREATE DATABASE LOCADORA;
GO
USE LOCADORA;
GO
CREATE TABLE CLIENTE(
	CODIGO INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	LOGRADOURO VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	UF CHAR(2) NOT NULL,
	CEP CHAR(8) NOT NULL,
	CELULAR CHAR(11) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CPF CHAR(11) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(CODIGO),
	CONSTRAINT CK_CLIENTE_CEP CHECK(LEN(CEP)=8),
	CONSTRAINT CK_CLIENTE_UF CHECK(UF IN('RO','AC','AM','RR','PA','AP','TO','MA','PI',
		'CE','RN','PB','PE','AL','SE','BA','MG','ES','RJ','SP','PR','SC','RS','MS','MT','GO','DF')),
	CONSTRAINT CK_CLIENTE_CELULAR CHECK(LEN(CELULAR)=11),
	CONSTRAINT CK_CLIENTE_DATA_NASCIMENTO 
		CHECK(DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())>=18),
	CONSTRAINT UQ_CLIENTE_EMAIL UNIQUE(EMAIL),
	CONSTRAINT UQ_CLIENTE_CPF UNIQUE(CPF),
	CONSTRAINT UQ_CLIENTE_CELULAR UNIQUE(CELULAR),
	CONSTRAINT CK_CLIENTE_CPF CHECK(LEN(CPF)=11)
);
GO

-- PEGANDO O ANO ATUAL
--SELECT DATEPART(YEAR,GETDATE())
--SELECT YEAR(GETDATE())

CREATE TABLE VEICULO(
	CODIGO INT NOT NULL IDENTITY(1,1),
	PLACA CHAR(7) NOT NULL,
	MARCA VARCHAR(30) NOT NULL,
	MODELO VARCHAR(30) NOT NULL,
	ANO SMALLINT NOT NULL,
	VALOR_DIARIA REAL NOT NULL,
	KM INT NOT NULL,
	CONSTRAINT PK_VEICULO PRIMARY KEY(CODIGO),
	CONSTRAINT UQ_VEICULO_PLACA UNIQUE(PLACA),
	CONSTRAINT CK_VEICULO_PLACA CHECK(LEN(PLACA)=7),
	CONSTRAINT CK_VEICULO_ANO 
   	   CHECK( ANO<= YEAR(GETDATE()) AND (YEAR(GETDATE())-ANO)<=10 )
);
GO
CREATE TABLE LOCACAO(
	CODIGO INT NOT NULL IDENTITY(1,2),
	COD_VEICULO INT NOT NULL,
	COD_CLIENTE INT NOT NULL,
	DATA_HORA_RETIRADA DATETIME NOT NULL,
	DATA_HORA_DEVOLUCAO DATETIME NULL,
	VALOR_TOTAL REAL NULL,
	CONSTRAINT PK_LOCACAO PRIMARY KEY(CODIGO),
	CONSTRAINT FK_LOCACAO_VEICULO FOREIGN KEY(COD_VEICULO) REFERENCES VEICULO(CODIGO),
	CONSTRAINT FK_LOCACAO_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(CODIGO),
	CONSTRAINT CK_LOCACAO_DATA_HORA_DEVOLUCAO 
		CHECK(DATA_HORA_DEVOLUCAO IS NULL OR DATA_HORA_DEVOLUCAO>DATA_HORA_RETIRADA)
);
