-- FUNÇÃO DATEADD - CALCULA UMA NOVA DATA COM BASE EM UMA DATA INICIAL
-- EXEMPLO 1: ACRESCENTA 1.000 DIAS NA DATA ATUAL
SELECT DATEADD(DAY,1000,GETDATE());

-- EXEMPLO 2: SUBTRAI 500 MESES DA DATA ATUAL
SELECT DATEADD(MONTH,-500,GETDATE());

