-- DML - DATA MANIPULATION LANGUAGE (LINGUAGEM DE MANIPULAÇÃO DE DADOS)
-- 4 OPERAÇÕES BÁSICAS: INCLUSÃO, EXCLUSÃO, ALTERAÇÃO E CONSULTA
-- SELECT - EXEMPLOS

-- * = TODAS AS COLUNAS
SELECT * FROM FUNCIONARIO;

-- ESPECIFICANDO AS COLUNAS DO RESULTADO
SELECT CODIGO, NOME, SEXO, SALARIO, CIDADE FROM FUNCIONARIO;

-- APRESENTE O CÓDIGO, NOME E DATA DE NASCIMENTO, ATIVO E CIDADE 
-- DE TODOS OS FUNCIONÁRIOS ATIVOS DA CIDADE DE TAQUARITINGA
SELECT CODIGO, NOME, DATA_NASCIMENTO, ATIVO, CIDADE FROM FUNCIONARIO
WHERE ATIVO=1 AND CIDADE='TAQUARITINGA';

-- RETORNE CÓDIGO, NOME, DATA DE NASCIMENTO, SEXO, ATIVO E CIDADE 
-- DOS FUNCIONÁRIOS. CONSIDERE SOMENTE FUNCIONÁRIOS ATIVOS 
-- DA CIDADE DE TAQUARITINGA. ORDENE EM ORDEM CRESCENTE DE NOME
SELECT CODIGO, NOME, DATA_NASCIMENTO, SEXO, ATIVO, CIDADE 
FROM FUNCIONARIO
WHERE ATIVO=1 AND CIDADE='TAQUARITINGA'
ORDER BY NOME;

-- * EM ORDEM DECRESCENTE DE NOME
SELECT CODIGO, NOME, DATA_NASCIMENTO, SEXO, ATIVO, CIDADE 
FROM FUNCIONARIO
WHERE ATIVO=1 AND CIDADE='TAQUARITINGA'
ORDER BY NOME DESC;

-- * EM ORDEM DECRESCENTE DE SEXO E CRESCENTE DE NOME
SELECT CODIGO, NOME, DATA_NASCIMENTO, SEXO, ATIVO, CIDADE 
FROM FUNCIONARIO
WHERE ATIVO=1 AND CIDADE='TAQUARITINGA'
-- ORDER BY SEXO DESC, NOME ASC
ORDER BY 4 DESC, 2 ASC;

-- * EM ORDEM DECRESCENTE DE SALARIO E CRESCENTE DE NOME
SELECT CODIGO, NOME, DATA_NASCIMENTO, SEXO, ATIVO, CIDADE
FROM FUNCIONARIO
WHERE ATIVO=1 AND CIDADE='TAQUARITINGA'
-- ORDER BY SEXO DESC, NOME ASC
ORDER BY SALARIO DESC, 2 ASC;

-- EXEMPLO: RETORNE CÓDIGO, NOME, DATA DE NASCIMENTO, IDADE, SEXO E CIDADE 
-- DOS FUNCIONÁRIOS. CONSIDERE SOMENTE FUNCIONÁRIOS ATIVOS COM IDADE ENTRE 18 E 29 ANOS.
-- ORDENE POR ORDEM CRESCENTE DE IDADE E NOME.
SELECT CODIGO
	, NOME
	, DATA_NASCIMENTO DATA_NASC
	, DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) IDADE
	, SEXO
	, CIDADE
FROM FUNCIONARIO
WHERE ATIVO=1 AND DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) BETWEEN 18 AND 29;

-- EXERCÍCIO
-- APRESENTE O NOME DO PROJETO, A DATA DE INICIO, A DATA DE TERMINO,  
-- A QUANTOS MESES O PROJETO FOI INICIADO, E QUANTOS MESES LEVOU DE SEU INICIO  ATÉ SEU TÉRMINO. 
-- CONSIDERE SOMENTE PROJETOS COM DATA DE TÉRMINO DEFINIDA (NÃO NULA).  
-- ORDENE POR NOME DE PROJETO (DECRESCENTE).
